version: '3'

services:
    redis: 
        image: 'redis:3.2-alpine'
        ports:
            - '6379:6379'
            # the - represents a list so could add more ports if needed
        volumes:
            - 'redis:/data'
    web:
        build: '.'
        env_file:
            - '.env' #loads env files
        depends_on:
            - 'redis' #will start redis before web container
        #images: 'bs009/web:1.0'
        ports:
            - '5000:5000'
        volumes:
            - '.:/app'

volumes:
    redis: {}